version: '3.8'

services:
  mongo:
    image: mongo:4.4.3
    container_name: db
    volumes:
    - mongodb:/data/db
    - mongodb_config:/data/configdb
    ports:
    - '27017:27017'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
    - '8000:80'
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config:
